# Generated by Django 3.1.5 on 2021-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inUrl', models.CharField(max_length=120)),
                ('urlResponse', models.CharField(max_length=2000)),
            ],
        ),
    ]
